In [48]:
import pandas as pd

In [49]:
df = pd.read_csv("baseball_positions.csv")
df.head()

            Name Team Position
0    Aaron Judge  NYY    OF/DH
1    Cal Raleigh  SEA     C/DH
2  Shohei Ohtani  LAD       DH
3      Juan Soto  NYM       OF
4   Tarik Skubal  DET       SP

In [50]:
df['positions_list'] = df['Position'].str.split('/')

df_exploded = df.explode('positions_list')
df_exploded.reset_index(drop=True)
df_exploded.head()

            Name Team Position positions_list
0    Aaron Judge  NYY    OF/DH             OF
0    Aaron Judge  NYY    OF/DH             DH
1    Cal Raleigh  SEA     C/DH              C
1    Cal Raleigh  SEA     C/DH             DH
2  Shohei Ohtani  LAD       DH             DH

In [51]:
df_group = df_exploded.groupby('positions_list').agg({"positions_list": "count"})\
        .rename(columns={"positions_list": "positions_list_counter"})\
        .reset_index()
df_group = df_group.sort_values("positions_list_counter", ascending=False)

In [52]:
df_group.head()

  positions_list  positions_list_counter
5             OF                     294
7             SP                     227
6             RP                     222
4             DH                     134
2             3B                     127