In [61]:
import pandas as pd
from collections import defaultdict
from operator import attrgetter

In [62]:
df = pd.read_csv("grocery_transactions.csv")
df.head()

,transaction_id,transaction_datetime,register,line_item,upc,product_name,quantity,unit_price
0,1,2024-01-01 07:14:33,2,1,40000591512,Eggs,2,4.29
1,1,2024-01-01 07:14:33,2,2,40001330902,Milk,1,3.49
2,2,2024-01-01 07:32:13,8,1,40001626658,Parmesan,1,5.49
3,2,2024-01-01 07:32:13,8,2,40001700597,Pasta,1,1.79
4,2,2024-01-01 07:32:13,8,3,40001774536,Pasta Sauce,1,3.29

In [63]:
paired_df = pd.merge(df[['transaction_id', 'product_name']], df[['transaction_id', 'product_name']], on='transaction_id', how='outer')
paired_df = paired_df[paired_df['product_name_x'] != paired_df['product_name_y']]
paired_df.head()

   transaction_id product_name_x product_name_y
1               1           Eggs           Milk
2               1           Milk           Eggs
5               2       Parmesan          Pasta
6               2       Parmesan    Pasta Sauce
7               2       Parmesan         Yogurt

In [64]:
counter_hm = defaultdict(int) # counter dictionary for counting pairs
for product_name_x, product_name_y in zip(paired_df['product_name_x'], paired_df['product_name_y']):
    counter_hm[frozenset([product_name_x, product_name_y])] += 1

# correct products pairs that are counted twice
for k, v in counter_hm.items():
    counter_hm[k] = int(counter_hm[k]/2)

In [65]:
class product_pairs:
    def __init__(self, s : frozenset, pairs_count):
        self.s = s
        self.pairs_count = pairs_count
    def __str__(self):
        return f"{self.s} pair has count: {self.pairs_count}"

pairs_list = []
for k, v in counter_hm.items():
    pairs_list.append(product_pairs(k, v))
result = sorted(pairs_list, key=attrgetter('pairs_count'), reverse=True)
for pair in result:
    print(pair)

frozenset({'Salsa', 'Tortilla Chips'}) pair has count: 5358
frozenset({'Milk', 'Bananas'}) pair has count: 4483
frozenset({'Bread', 'Bananas'}) pair has count: 2970
frozenset({'Salsa', 'Bananas'}) pair has count: 2874
frozenset({'Bananas', 'Tortilla Chips'}) pair has count: 2857
frozenset({'Eggs', 'Bananas'}) pair has count: 2828
frozenset({'Bread', 'Milk'}) pair has count: 2706
frozenset({'Guacamole', 'Tortilla Chips'}) pair has count: 2633
frozenset({'Soda', 'Tortilla Chips'}) pair has count: 2630
frozenset({'Salsa', 'Soda'}) pair has count: 2627
frozenset({'Milk', 'Salsa'}) pair has count: 2623
frozenset({'Salsa', 'Guacamole'}) pair has count: 2618
frozenset({'Milk', 'Tortilla Chips'}) pair has count: 2614
frozenset({'Eggs', 'Milk'}) pair has count: 2451
frozenset({'Pasta Sauce', 'Pasta'}) pair has count: 1988
frozenset({'Bread', 'Salsa'}) pair has count: 1733
frozenset({'Bread', 'Tortilla Chips'}) pair has count: 1732
frozenset({'Eggs', 'Salsa'}) pair has count: 1665
frozenset({'Bread', 'Eggs'}) pair has count: 1663
frozenset({'Eggs', 'Tortilla Chips'}) pair has count: 1643
frozenset({'Coffee Creamer', 'Ground Coffee'}) pair has count: 1628
frozenset({'Ground Beef', 'Burger Buns'}) pair has count: 1603
frozenset({'Pancake Mix', 'Maple Syrup'}) pair has count: 1571
frozenset({'Peanut Butter', 'Jelly'}) pair has count: 1563
frozenset({'Soda', 'Bananas'}) pair has count: 1426
frozenset({'Guacamole', 'Bananas'}) pair has count: 1388
frozenset({'Milk', 'Guacamole'}) pair has count: 1317
frozenset({'Soda', 'Guacamole'}) pair has count: 1290
frozenset({'Milk', 'Soda'}) pair has count: 1268
frozenset({'Pasta', 'Bananas'}) pair has count: 1090
frozenset({'Pasta Sauce', 'Bananas'}) pair has count: 1083
frozenset({'Milk', 'Pasta'}) pair has count: 970
frozenset({'Parmesan', 'Pasta'}) pair has count: 943
frozenset({'Pasta Sauce', 'Milk'}) pair has count: 942
frozenset({'Pasta Sauce', 'Parmesan'}) pair has count: 927
frozenset({'Ground Coffee', 'Bananas'}) pair has count: 903
frozenset({'Coffee Creamer', 'Bananas'}) pair has count: 893
frozenset({'Bread', 'Guacamole'}) pair has count: 887
frozenset({'Bananas', 'Burger Buns'}) pair has count: 864
frozenset({'Pancake Mix', 'Bananas'}) pair has count: 861
frozenset({'Ground Beef', 'Bananas'}) pair has count: 860
frozenset({'Peanut Butter', 'Bananas'}) pair has count: 857
frozenset({'Jelly', 'Bananas'}) pair has count: 850
frozenset({'Maple Syrup', 'Bananas'}) pair has count: 845
frozenset({'Frozen Pizza', 'Bananas'}) pair has count: 844
frozenset({'Carrots', 'Bananas'}) pair has count: 837
frozenset({'Bread', 'Soda'}) pair has count: 837
frozenset({'Tomatoes', 'Bananas'}) pair has count: 828
frozenset({'Coffee Creamer', 'Milk'}) pair has count: 821
frozenset({'Ice Cream', 'Bananas'}) pair has count: 820
frozenset({'Bananas', 'Dish Soap'}) pair has count: 818
frozenset({'Milk', 'Ground Coffee'}) pair has count: 815
frozenset({'Apples', 'Bananas'}) pair has count: 815
frozenset({'Rice', 'Bananas'}) pair has count: 814
frozenset({'Eggs', 'Soda'}) pair has count: 807
frozenset({'Eggs', 'Guacamole'}) pair has count: 807
frozenset({'Paper Towels', 'Bananas'}) pair has count: 802
frozenset({'Yogurt', 'Bananas'}) pair has count: 797
frozenset({'Pancake Mix', 'Milk'}) pair has count: 792
frozenset({'Bananas', 'Chicken Breast'}) pair has count: 785
frozenset({'Ground Beef', 'Ketchup'}) pair has count: 782
frozenset({'Milk', 'Maple Syrup'}) pair has count: 782
frozenset({'Ketchup', 'Burger Buns'}) pair has count: 780
frozenset({'Peanut Butter', 'Milk'}) pair has count: 778
frozenset({'Bananas', 'Lettuce'}) pair has count: 777
frozenset({'Jelly', 'Milk'}) pair has count: 775
frozenset({'Onions', 'Bananas'}) pair has count: 775
frozenset({'Frozen Pizza', 'Milk'}) pair has count: 769
frozenset({'Yogurt', 'Milk'}) pair has count: 751
frozenset({'Milk', 'Carrots'}) pair has count: 748
frozenset({'Milk', 'Burger Buns'}) pair has count: 739
frozenset({'Milk', 'Dish Soap'}) pair has count: 739
frozenset({'Ground Beef', 'Milk'}) pair has count: 738
frozenset({'Tomatoes', 'Milk'}) pair has count: 729
frozenset({'Milk', 'Paper Towels'}) pair has count: 728
frozenset({'Milk', 'Lettuce'}) pair has count: 718
frozenset({'Onions', 'Milk'}) pair has count: 717
frozenset({'Milk', 'Chicken Breast'}) pair has count: 716
frozenset({'Milk', 'Ice Cream'}) pair has count: 713
frozenset({'Apples', 'Milk'}) pair has count: 711
frozenset({'Rice', 'Milk'}) pair has count: 710
frozenset({'Bread', 'Pasta'}) pair has count: 663
frozenset({'Bread', 'Pasta Sauce'}) pair has count: 663
frozenset({'Eggs', 'Pasta'}) pair has count: 595
frozenset({'Pasta Sauce', 'Eggs'}) pair has count: 594
frozenset({'Coffee Creamer', 'Bread'}) pair has count: 533
frozenset({'Bread', 'Tomatoes'}) pair has count: 529
frozenset({'Frozen Pizza', 'Salsa'}) pair has count: 529
frozenset({'Tomatoes', 'Salsa'}) pair has count: 527
frozenset({'Bread', 'Ground Coffee'}) pair has count: 526
frozenset({'Bread', 'Carrots'}) pair has count: 523
frozenset({'Frozen Pizza', 'Tortilla Chips'}) pair has count: 522
frozenset({'Tomatoes', 'Tortilla Chips'}) pair has count: 520
frozenset({'Parmesan', 'Bananas'}) pair has count: 518
frozenset({'Bread', 'Jelly'}) pair has count: 511
frozenset({'Bread', 'Pancake Mix'}) pair has count: 508
frozenset({'Bread', 'Peanut Butter'}) pair has count: 507
frozenset({'Onions', 'Salsa'}) pair has count: 507
frozenset({'Bread', 'Maple Syrup'}) pair has count: 505
frozenset({'Onions', 'Tortilla Chips'}) pair has count: 503
frozenset({'Coffee Creamer', 'Eggs'}) pair has count: 502
frozenset({'Ground Beef', 'Bread'}) pair has count: 499
frozenset({'Bread', 'Lettuce'}) pair has count: 498
frozenset({'Bread', 'Yogurt'}) pair has count: 498
frozenset({'Pancake Mix', 'Eggs'}) pair has count: 496
frozenset({'Carrots', 'Tortilla Chips'}) pair has count: 494
frozenset({'Salsa', 'Ice Cream'}) pair has count: 493
frozenset({'Eggs', 'Ground Coffee'}) pair has count: 492
frozenset({'Bread', 'Burger Buns'}) pair has count: 492
frozenset({'Bread', 'Dish Soap'}) pair has count: 489
frozenset({'Bread', 'Chicken Breast'}) pair has count: 487
frozenset({'Bread', 'Frozen Pizza'}) pair has count: 487
frozenset({'Bread', 'Onions'}) pair has count: 487
frozenset({'Bread', 'Rice'}) pair has count: 486
frozenset({'Salsa', 'Chicken Breast'}) pair has count: 485
frozenset({'Ice Cream', 'Tortilla Chips'}) pair has count: 484
frozenset({'Eggs', 'Maple Syrup'}) pair has count: 484
frozenset({'Tortilla Chips', 'Chicken Breast'}) pair has count: 483
frozenset({'Bread', 'Ice Cream'}) pair has count: 481
frozenset({'Bread', 'Paper Towels'}) pair has count: 479
frozenset({'Apples', 'Bread'}) pair has count: 477
frozenset({'Eggs', 'Carrots'}) pair has count: 476
frozenset({'Salsa', 'Carrots'}) pair has count: 476
frozenset({'Eggs', 'Ice Cream'}) pair has count: 475
frozenset({'Paper Towels', 'Tortilla Chips'}) pair has count: 472
frozenset({'Eggs', 'Burger Buns'}) pair has count: 471
frozenset({'Ground Beef', 'Eggs'}) pair has count: 470
frozenset({'Eggs', 'Yogurt'}) pair has count: 470
frozenset({'Peanut Butter', 'Eggs'}) pair has count: 464
frozenset({'Rice', 'Tortilla Chips'}) pair has count: 463
frozenset({'Jelly', 'Eggs'}) pair has count: 463
frozenset({'Salsa', 'Paper Towels'}) pair has count: 458
frozenset({'Rice', 'Salsa'}) pair has count: 458
frozenset({'Apples', 'Tortilla Chips'}) pair has count: 457
frozenset({'Yogurt', 'Salsa'}) pair has count: 456
frozenset({'Onions', 'Eggs'}) pair has count: 455
frozenset({'Tortilla Chips', 'Dish Soap'}) pair has count: 452
frozenset({'Eggs', 'Paper Towels'}) pair has count: 452
frozenset({'Apples', 'Salsa'}) pair has count: 452
frozenset({'Lettuce', 'Tortilla Chips'}) pair has count: 449
frozenset({'Salsa', 'Lettuce'}) pair has count: 447
frozenset({'Yogurt', 'Tortilla Chips'}) pair has count: 446
frozenset({'Salsa', 'Dish Soap'}) pair has count: 445
frozenset({'Tomatoes', 'Eggs'}) pair has count: 444
frozenset({'Eggs', 'Dish Soap'}) pair has count: 443
frozenset({'Eggs', 'Lettuce'}) pair has count: 441
frozenset({'Parmesan', 'Milk'}) pair has count: 441
frozenset({'Eggs', 'Frozen Pizza'}) pair has count: 441
frozenset({'Eggs', 'Chicken Breast'}) pair has count: 431
frozenset({'Apples', 'Eggs'}) pair has count: 428
frozenset({'Rice', 'Eggs'}) pair has count: 422
frozenset({'Ketchup', 'Bananas'}) pair has count: 419
frozenset({'Milk', 'Ketchup'}) pair has count: 373
frozenset({'Bread', 'Parmesan'}) pair has count: 311
frozenset({'Eggs', 'Parmesan'}) pair has count: 273
frozenset({'Soda', 'Ice Cream'}) pair has count: 271
frozenset({'Frozen Pizza', 'Soda'}) pair has count: 261
frozenset({'Bread', 'Ketchup'}) pair has count: 260
frozenset({'Tomatoes', 'Soda'}) pair has count: 259
frozenset({'Onions', 'Soda'}) pair has count: 247
frozenset({'Eggs', 'Ketchup'}) pair has count: 244
frozenset({'Onions', 'Guacamole'}) pair has count: 244
frozenset({'Frozen Pizza', 'Guacamole'}) pair has count: 244
frozenset({'Soda', 'Lettuce'}) pair has count: 243
frozenset({'Carrots', 'Guacamole'}) pair has count: 242
frozenset({'Tomatoes', 'Guacamole'}) pair has count: 236
frozenset({'Soda', 'Chicken Breast'}) pair has count: 234
frozenset({'Guacamole', 'Chicken Breast'}) pair has count: 231
frozenset({'Guacamole', 'Ice Cream'}) pair has count: 229
frozenset({'Carrots', 'Soda'}) pair has count: 227
frozenset({'Soda', 'Dish Soap'}) pair has count: 225
frozenset({'Apples', 'Guacamole'}) pair has count: 225
frozenset({'Paper Towels', 'Soda'}) pair has count: 224
frozenset({'Yogurt', 'Guacamole'}) pair has count: 224
frozenset({'Paper Towels', 'Guacamole'}) pair has count: 223
frozenset({'Yogurt', 'Soda'}) pair has count: 221
frozenset({'Guacamole', 'Lettuce'}) pair has count: 218
frozenset({'Guacamole', 'Dish Soap'}) pair has count: 217
frozenset({'Apples', 'Soda'}) pair has count: 214
frozenset({'Rice', 'Soda'}) pair has count: 213
frozenset({'Rice', 'Guacamole'}) pair has count: 204
frozenset({'Rice', 'Pasta'}) pair has count: 196
frozenset({'Pasta Sauce', 'Rice'}) pair has count: 194
frozenset({'Apples', 'Pasta'}) pair has count: 193
frozenset({'Apples', 'Pasta Sauce'}) pair has count: 189
frozenset({'Carrots', 'Pasta'}) pair has count: 184
frozenset({'Pasta Sauce', 'Carrots'}) pair has count: 183
frozenset({'Pasta Sauce', 'Yogurt'}) pair has count: 182
frozenset({'Frozen Pizza', 'Pasta'}) pair has count: 179
frozenset({'Yogurt', 'Pasta'}) pair has count: 178
frozenset({'Onions', 'Pasta'}) pair has count: 177
frozenset({'Pasta', 'Dish Soap'}) pair has count: 177
frozenset({'Pasta Sauce', 'Chicken Breast'}) pair has count: 174
frozenset({'Paper Towels', 'Pasta'}) pair has count: 173
frozenset({'Pasta', 'Chicken Breast'}) pair has count: 172
frozenset({'Onions', 'Pasta Sauce'}) pair has count: 172
frozenset({'Pasta Sauce', 'Frozen Pizza'}) pair has count: 171
frozenset({'Pasta Sauce', 'Dish Soap'}) pair has count: 169
frozenset({'Pasta', 'Ice Cream'}) pair has count: 168
frozenset({'Pasta Sauce', 'Ice Cream'}) pair has count: 166
frozenset({'Pasta', 'Lettuce'}) pair has count: 165
frozenset({'Coffee Creamer', 'Dish Soap'}) pair has count: 161
frozenset({'Ground Coffee', 'Dish Soap'}) pair has count: 161
frozenset({'Pancake Mix', 'Carrots'}) pair has count: 159
frozenset({'Pasta Sauce', 'Lettuce'}) pair has count: 159
frozenset({'Jelly', 'Dish Soap'}) pair has count: 158
frozenset({'Pasta Sauce', 'Paper Towels'}) pair has count: 158
frozenset({'Tomatoes', 'Ground Coffee'}) pair has count: 157
frozenset({'Ground Beef', 'Lettuce'}) pair has count: 157
frozenset({'Coffee Creamer', 'Chicken Breast'}) pair has count: 156
frozenset({'Ground Coffee', 'Chicken Breast'}) pair has count: 155
frozenset({'Lettuce', 'Burger Buns'}) pair has count: 155
frozenset({'Peanut Butter', 'Dish Soap'}) pair has count: 154
frozenset({'Carrots', 'Maple Syrup'}) pair has count: 152
frozenset({'Coffee Creamer', 'Yogurt'}) pair has count: 151
frozenset({'Yogurt', 'Ground Coffee'}) pair has count: 151
frozenset({'Coffee Creamer', 'Tomatoes'}) pair has count: 150
frozenset({'Ice Cream', 'Burger Buns'}) pair has count: 150
frozenset({'Ground Beef', 'Ice Cream'}) pair has count: 150
frozenset({'Tomatoes', 'Pasta'}) pair has count: 149
frozenset({'Rice', 'Ground Coffee'}) pair has count: 147
frozenset({'Ground Beef', 'Dish Soap'}) pair has count: 146
frozenset({'Peanut Butter', 'Tomatoes'}) pair has count: 146
frozenset({'Ground Beef', 'Chicken Breast'}) pair has count: 146
frozenset({'Yogurt', 'Burger Buns'}) pair has count: 145
frozenset({'Ground Beef', 'Yogurt'}) pair has count: 145
frozenset({'Pancake Mix', 'Lettuce'}) pair has count: 145
frozenset({'Coffee Creamer', 'Paper Towels'}) pair has count: 145
frozenset({'Peanut Butter', 'Paper Towels'}) pair has count: 145
frozenset({'Pasta Sauce', 'Tomatoes'}) pair has count: 145
frozenset({'Frozen Pizza', 'Ground Coffee'}) pair has count: 145
frozenset({'Jelly', 'Paper Towels'}) pair has count: 144
frozenset({'Apples', 'Maple Syrup'}) pair has count: 144
frozenset({'Apples', 'Pancake Mix'}) pair has count: 144
frozenset({'Maple Syrup', 'Dish Soap'}) pair has count: 143
frozenset({'Tomatoes', 'Jelly'}) pair has count: 143
frozenset({'Pancake Mix', 'Paper Towels'}) pair has count: 143
frozenset({'Ground Beef', 'Paper Towels'}) pair has count: 143
frozenset({'Chicken Breast', 'Burger Buns'}) pair has count: 143
frozenset({'Paper Towels', 'Ground Coffee'}) pair has count: 142
frozenset({'Jelly', 'Frozen Pizza'}) pair has count: 142
frozenset({'Jelly', 'Chicken Breast'}) pair has count: 142
frozenset({'Coffee Creamer', 'Frozen Pizza'}) pair has count: 141
frozenset({'Pancake Mix', 'Ice Cream'}) pair has count: 141
frozenset({'Coffee Creamer', 'Rice'}) pair has count: 140
frozenset({'Maple Syrup', 'Chicken Breast'}) pair has count: 140
frozenset({'Jelly', 'Ice Cream'}) pair has count: 140
frozenset({'Dish Soap', 'Burger Buns'}) pair has count: 139
frozenset({'Pancake Mix', 'Dish Soap'}) pair has count: 139
frozenset({'Peanut Butter', 'Ice Cream'}) pair has count: 139
frozenset({'Peanut Butter', 'Yogurt'}) pair has count: 139
frozenset({'Peanut Butter', 'Chicken Breast'}) pair has count: 139
frozenset({'Peanut Butter', 'Frozen Pizza'}) pair has count: 138
frozenset({'Pancake Mix', 'Yogurt'}) pair has count: 138
frozenset({'Pancake Mix', 'Frozen Pizza'}) pair has count: 138
frozenset({'Rice', 'Maple Syrup'}) pair has count: 138
frozenset({'Paper Towels', 'Maple Syrup'}) pair has count: 138
frozenset({'Peanut Butter', 'Carrots'}) pair has count: 137
frozenset({'Peanut Butter', 'Lettuce'}) pair has count: 137
frozenset({'Coffee Creamer', 'Lettuce'}) pair has count: 137
frozenset({'Ground Coffee', 'Lettuce'}) pair has count: 137
frozenset({'Maple Syrup', 'Lettuce'}) pair has count: 136
frozenset({'Pancake Mix', 'Chicken Breast'}) pair has count: 136
frozenset({'Yogurt', 'Maple Syrup'}) pair has count: 136
frozenset({'Ground Beef', 'Rice'}) pair has count: 136
frozenset({'Apples', 'Ground Beef'}) pair has count: 136
frozenset({'Jelly', 'Carrots'}) pair has count: 135
frozenset({'Pancake Mix', 'Rice'}) pair has count: 135
frozenset({'Paper Towels', 'Burger Buns'}) pair has count: 135
frozenset({'Peanut Butter', 'Rice'}) pair has count: 135
frozenset({'Ground Beef', 'Carrots'}) pair has count: 135
frozenset({'Apples', 'Coffee Creamer'}) pair has count: 134
frozenset({'Jelly', 'Yogurt'}) pair has count: 134
frozenset({'Onions', 'Jelly'}) pair has count: 134
frozenset({'Onions', 'Peanut Butter'}) pair has count: 134
frozenset({'Coffee Creamer', 'Onions'}) pair has count: 133
frozenset({'Ground Beef', 'Tomatoes'}) pair has count: 133
frozenset({'Jelly', 'Lettuce'}) pair has count: 133
frozenset({'Maple Syrup', 'Ice Cream'}) pair has count: 133
frozenset({'Frozen Pizza', 'Maple Syrup'}) pair has count: 133
frozenset({'Ground Beef', 'Onions'}) pair has count: 133
frozenset({'Onions', 'Ground Coffee'}) pair has count: 132
frozenset({'Pancake Mix', 'Tomatoes'}) pair has count: 132
frozenset({'Apples', 'Jelly'}) pair has count: 132
frozenset({'Rice', 'Burger Buns'}) pair has count: 132
frozenset({'Onions', 'Burger Buns'}) pair has count: 132
frozenset({'Carrots', 'Ground Coffee'}) pair has count: 132
frozenset({'Rice', 'Jelly'}) pair has count: 132
frozenset({'Carrots', 'Burger Buns'}) pair has count: 132
frozenset({'Apples', 'Peanut Butter'}) pair has count: 131
frozenset({'Coffee Creamer', 'Ice Cream'}) pair has count: 131
frozenset({'Coffee Creamer', 'Carrots'}) pair has count: 130
frozenset({'Tomatoes', 'Burger Buns'}) pair has count: 130
frozenset({'Apples', 'Ground Coffee'}) pair has count: 129
frozenset({'Apples', 'Burger Buns'}) pair has count: 129
frozenset({'Ground Coffee', 'Ice Cream'}) pair has count: 128
frozenset({'Onions', 'Pancake Mix'}) pair has count: 126
frozenset({'Tomatoes', 'Maple Syrup'}) pair has count: 123
frozenset({'Onions', 'Maple Syrup'}) pair has count: 122
frozenset({'Frozen Pizza', 'Dish Soap'}) pair has count: 119
frozenset({'Ground Beef', 'Frozen Pizza'}) pair has count: 118
frozenset({'Ice Cream', 'Dish Soap'}) pair has count: 113
frozenset({'Frozen Pizza', 'Burger Buns'}) pair has count: 113
frozenset({'Apples', 'Dish Soap'}) pair has count: 109
frozenset({'Tomatoes', 'Frozen Pizza'}) pair has count: 105
frozenset({'Paper Towels', 'Chicken Breast'}) pair has count: 105
frozenset({'Apples', 'Onions'}) pair has count: 104
frozenset({'Frozen Pizza', 'Chicken Breast'}) pair has count: 104
frozenset({'Onions', 'Dish Soap'}) pair has count: 103
frozenset({'Carrots', 'Lettuce'}) pair has count: 102
frozenset({'Onions', 'Paper Towels'}) pair has count: 102
frozenset({'Frozen Pizza', 'Ice Cream'}) pair has count: 102
frozenset({'Rice', 'Yogurt'}) pair has count: 101
frozenset({'Ice Cream', 'Chicken Breast'}) pair has count: 101
frozenset({'Apples', 'Yogurt'}) pair has count: 100
frozenset({'Yogurt', 'Ice Cream'}) pair has count: 99
frozenset({'Rice', 'Parmesan'}) pair has count: 99
frozenset({'Rice', 'Ice Cream'}) pair has count: 98
frozenset({'Carrots', 'Ice Cream'}) pair has count: 98
frozenset({'Frozen Pizza', 'Paper Towels'}) pair has count: 98
frozenset({'Paper Towels', 'Lettuce'}) pair has count: 98
frozenset({'Lettuce', 'Dish Soap'}) pair has count: 98
frozenset({'Tomatoes', 'Lettuce'}) pair has count: 98
frozenset({'Apples', 'Lettuce'}) pair has count: 97
frozenset({'Rice', 'Frozen Pizza'}) pair has count: 95
frozenset({'Apples', 'Tomatoes'}) pair has count: 95
frozenset({'Yogurt', 'Carrots'}) pair has count: 95
frozenset({'Carrots', 'Chicken Breast'}) pair has count: 94
frozenset({'Yogurt', 'Chicken Breast'}) pair has count: 94
frozenset({'Tomatoes', 'Carrots'}) pair has count: 94
frozenset({'Rice', 'Carrots'}) pair has count: 94
frozenset({'Parmesan', 'Carrots'}) pair has count: 93
frozenset({'Onions', 'Rice'}) pair has count: 93
frozenset({'Frozen Pizza', 'Yogurt'}) pair has count: 93
frozenset({'Rice', 'Chicken Breast'}) pair has count: 92
frozenset({'Tomatoes', 'Chicken Breast'}) pair has count: 92
frozenset({'Apples', 'Parmesan'}) pair has count: 92
frozenset({'Onions', 'Lettuce'}) pair has count: 92
frozenset({'Yogurt', 'Paper Towels'}) pair has count: 92
frozenset({'Onions', 'Tomatoes'}) pair has count: 91
frozenset({'Yogurt', 'Dish Soap'}) pair has count: 91
frozenset({'Tomatoes', 'Ice Cream'}) pair has count: 91
frozenset({'Onions', 'Yogurt'}) pair has count: 91
frozenset({'Apples', 'Carrots'}) pair has count: 90
frozenset({'Tomatoes', 'Yogurt'}) pair has count: 90
frozenset({'Dish Soap', 'Chicken Breast'}) pair has count: 89
frozenset({'Yogurt', 'Lettuce'}) pair has count: 89
frozenset({'Carrots', 'Dish Soap'}) pair has count: 89
frozenset({'Tomatoes', 'Paper Towels'}) pair has count: 88
frozenset({'Onions', 'Carrots'}) pair has count: 88
frozenset({'Apples', 'Paper Towels'}) pair has count: 88
frozenset({'Parmesan', 'Yogurt'}) pair has count: 87
frozenset({'Rice', 'Lettuce'}) pair has count: 86
frozenset({'Rice', 'Tomatoes'}) pair has count: 86
frozenset({'Apples', 'Rice'}) pair has count: 86